### PR TITLE
Freecam Fixes

### LINKED ISSUE #26: Enable freecam in replays

### LINKED ISSUE #40: Freecam only works with the controller in Port 1
Maybe a selection could be added to choose which controller to use?

### PR DESCRIPTION
**Pull request by rehtropsmb**
* Freecam uses inputs from any controller (Fixes #40)
* Freecam works in replays (Fixes #26)
* Input Display values are clamped (holding down on two controllers used to draw the stick outside of the display, it doesn't anymore)
* ILBattle and Physics displays hide when Freecam Hide Hud Pref is active
* Fixed bug with Physics and Jump mod interaction

### CODE REVIEW

File: src/mods/freecam.cpp [hunk 1]
```diff
@@ -24,15 +24,55 @@ static S16Vec s_rot = {};
...
+        }
+
+        outInputs.rawX = CLAMP(outInputs.rawX, -128, 127);
+        outInputs.rawY = CLAMP(outInputs.rawY, -128, 127);
+        outInputs.substickX = CLAMP(outInputs.substickX, -128, 127);
+        outInputs.substickY = CLAMP(outInputs.substickY, -128, 127);
+        outInputs.triggerL = CLAMP(outInputs.triggerL, 0, 255);
+        outInputs.triggerR = CLAMP(outInputs.triggerR, 0, 255);
+    }
+}
```
Comment (ComplexPlane) [inline src/mods/freecam.cpp]: Nice. Think this would be worth commonizing across freecam and input display? Maybe it could go in `pad.cpp`

File: src/mods/freecam.cpp [hunk 2]
```diff
@@ -24,15 +24,55 @@ static S16Vec s_rot = {};
...
+
+static void get_merged_stick_inputs(MergedStickInputs& outInputs) {
+    outInputs = {};
+
+    // Accumulate stick inputs from all controllers since we don't always
+    // know which player is active, like in menus
+    // TODO account for d-pad control setting
+    if (!pad::get_exclusive_mode()) {
+        for (s32 i = 0; i < 4; i++) {
+            mkb::PADStatus& status = mkb::pad_status_groups[i].raw;
```
Comment (ComplexPlane) [inline src/mods/freecam.cpp]: Can use `LEN(mkb::pad_status_groups)`

File: src/mods/freecam.cpp (hunk 1 above)
Comment (rehtropsmb) [reply src/mods/freecam.cpp]: I wasn't too sure what they all had in common while I was first writing this so I was kinda afraid to change too much lol. I'll take a stab at it tomorrow though.

Comment (ComplexPlane) [reply src/mods/freecam.cpp]: It's not too too much in common so don't sweat it if it seems overkill. That being said if you do, having a per-analog-input-type getter might make sense (instead of computing a whole struct each time), to match the rest of the `pad` API

File: src/mods/freecam.cpp [hunk 3]
```diff
@@ -46,12 +50,18 @@ static void update_cam(mkb::Camera* camera, mkb::Ball* ball) {
...
+    pad::get_merged_stick(stick);
+    pad::get_merged_substick(substick);
+    pad::get_merged_triggers(trigger);
+
+    float stick_x = stick.x / 60.f;
+    float stick_y = stick.y / 60.f;
+    float substick_x = substick.x / 60.f;
+    float substick_y = substick.y / 60.f;
+    float trigger_left = trigger.l / 128.f;
+    float trigger_right = trigger.r / 128.f;
```
Comment (ComplexPlane) [inline src/mods/freecam.cpp]: Can we make these into range limits constants in `pad.h`?

File: src/mods/freecam.cpp [hunk 4]
```diff
@@ -2,6 +2,7 @@
 
 #include "mkb/mkb.h"
 
+#include "mkb/mkb2_ghidra.h"
```
Comment (ComplexPlane) [inline src/mods/freecam.cpp]: Remove

File: src/systems/pad.cpp [hunk 5]
```diff
@@ -19,6 +21,75 @@ static mkb::PadStatusGroup s_pad_status_groups[4];
...
+
+    out.x = CLAMP(out.x, -128, 127);
+    out.y = CLAMP(out.y, -128, 127);
+}
+
+void get_merged_raw_stick(StickInputs& out) {
+    out = {};
+    if (s_exclusive_mode) return;
+
+    for (s32 i = 0; i < 4; i++) {
```
Comment (ComplexPlane) [inline src/systems/pad.cpp]: `LEN(mkb::pad_status_groups`

File: src/systems/pad.cpp [hunk 6]
```diff
@@ -19,6 +21,75 @@ static mkb::PadStatusGroup s_pad_status_groups[4];
...
+    for (u32 i = 0; i < LEN(mkb::pad_status_groups); i++) {
+        mkb::PADStatus& status = mkb::pad_status_groups[i].raw;
+        if (status.err == mkb::PAD_ERR_NONE) {
+            out.x += status.stickX;
+            out.y += status.stickY;
+        }
+    }
+
+    out.x = CLAMP(out.x, -128, 127);
+    out.y = CLAMP(out.y, -128, 127);
```
Comment (ComplexPlane) [inline src/systems/pad.cpp]: Can we accumulate these inputs in `pad::tick()` instead of in the getters? It'll deduplicate some code here

File: src/systems/pad.h [hunk 7]
```diff
@@ -16,10 +16,21 @@ enum Dir {
...
+struct StickInputs {
+    s32 x;
+    s32 y;
+};
+
+struct TriggerInputs {
+    s32 l;
+    s32 r;
+};
+
```
Comment (ComplexPlane) [inline src/systems/pad.h]: I try to avoid giving types a plural name so referring to multiple isn't confusing, but not a huge deal. `StickInput` or `StickState` might work

File: src/systems/pad.cpp [hunk 8]
```diff
@@ -1,6 +1,8 @@
 #include "systems/pad.h"
 
 #include "mkb/mkb.h"
+#include "mkb/mkb2_ghidra.h"
```
Comment (ComplexPlane) [inline src/systems/pad.cpp]: Remove

**Review by ComplexPlane — COMMENTED** [review]
Just minor nitpicks

File: src/systems/pad.cpp (hunk 6 above)
Comment (rehtropsmb) [reply src/systems/pad.cpp]: Yup, cleaned it up a bit, let me know if there's anything else I should change!

File: src/mods/inputdisp.cpp [hunk 9]
```diff
@@ -138,43 +112,39 @@ void init() {
...
         notch_found = true;
-    } else if (stick_inputs.gameX == -60 && stick_inputs.gameY == 60) {
+    } else if (stick_inputs.x == -60 && stick_inputs.y == 60) {
         *out_pos = {-DIAG, DIAG};
         notch_found = true;
-    } else if (stick_inputs.gameX == -60 && stick_inputs.gameY == -60) {
+    } else if (stick_inputs.x == -60 && stick_inputs.y == -60) {
         *out_pos = {-DIAG, -DIAG};
         notch_found = true;
     }
```
Comment (ComplexPlane) [inline src/mods/inputdisp.cpp]: These can use `MAX_STICK` too (might want to make those constants integer types and cast to float when needed)

File: src/systems/pad.cpp [hunk 10]
```diff
@@ -259,12 +292,38 @@ void tick() {
...
+            }
+        }
+        s_analog_state.raw_stick_x = CLAMP(s_analog_state.raw_stick_x, -128, 127);
+        s_analog_state.raw_stick_y = CLAMP(s_analog_state.raw_stick_y, -128, 127);
+        s_analog_state.stick_x = CLAMP(s_analog_state.stick_x, -60, 60);
+        s_analog_state.stick_y = CLAMP(s_analog_state.stick_y, -60, 60);
+        s_analog_state.substick_x = CLAMP(s_analog_state.substick_x, -60, 60);
+        s_analog_state.substick_y = CLAMP(s_analog_state.substick_y, -60, 60);
+        s_analog_state.trigger_l = CLAMP(s_analog_state.trigger_l, 0, 255);
+        s_analog_state.trigger_r = CLAMP(s_analog_state.trigger_r, 0, 255);
```
Comment (ComplexPlane) [inline src/systems/pad.cpp]: Use `MAX_STICK` and `MAX_TRIGGER`

File: src/mods/freecam.cpp [hunk 11]
```diff
@@ -18,6 +18,9 @@ enum {
 };
 }
 
+static constexpr float MAX_STICK = 60.f;
+static constexpr float MAX_TRIGGER = 128.f;
+
```
Comment (ComplexPlane) [inline src/mods/freecam.cpp]: These should go in `pad.h`

File: src/systems/pad.h [hunk 12]
```diff
@@ -16,10 +16,24 @@ enum Dir {
...
+    s32 y;
+};
+
+struct TriggerState {
+    s32 l;
+    s32 r;
+};
+
+static constexpr int MAX_STICK = 60.f;
+static constexpr int MAX_TRIGGER = 128.f;
```
Comment (ComplexPlane) [inline src/systems/pad.h]: they still floats tho :(
